theme = "dracula"

[editor]
bufferline = "always"
text-width = 96
cursorline = true
rulers = [96]
true-color = true
line-number = "relative"

[editor.indent-guides]
render = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.statusline]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"
center = ["version-control"]
left = ["mode", "spinner", "file-name", "read-only-indicator"]

[keys.normal]
"A-w" = ":buffer-close"
"A-/" = "repeat_last_motion"
"A-," = "goto_previous_buffer"
"A-." = "goto_next_buffer"
"C-s" = [":w"]

[keys.select]
"C-s" = ["normal_mode", ":w"]

[keys.insert]
"C-s" = ["normal_mode", ":w"]
"C-space" = "completion"
"A-x" = "normal_mode"  
