[[language]]
name = "bash"
language-servers = [ "bash-language-server" ]
formatter = { command = "shfmt" }
indent = { tab-width = 2, unit = "\t" }
auto-format = true

[language-server.bash-language-server]
command = "bash-language-server"
args = ["start"]

[[language]]
name = "go"
formatter = { command = "goimports" }
indent = { tab-width = 2, unit = "\t" }
auto-format = true

[[language]]
name = "javascript"
language-servers = [ "typescript-language-server", "eslint" ]
formatter = { command = "prettier", args = [ "--parser", "typescript" ] }
indent = { tab-width = 2, unit = "\t" }
auto-format = true

[[language]]
name = "jsx"
language-servers = [ "typescript-language-server", "eslint" ]
formatter = { command = "prettier", args = [ "--parser", "typescript" ] }
indent = { tab-width = 2, unit = "\t" }
auto-format = true

[[language]]
name = "tsx"
language-servers = [ "typescript-language-server", "eslint" ]
formatter = { command = "prettier", args = [ "--parser", "typescript" ] }
indent = { tab-width = 2, unit = "\t" }
auto-format = true

[[language]]
name = "html"
formatter = { command = 'prettier', args = ["--parser", "html"] }

[[language]]
name = "json"
formatter = { command = 'prettier', args = ["--parser", "json"] }

[[language]]
name = "css"
formatter = { command = 'prettier', args = ["--parser", "css"] }
