theme = "dracula"

[editor]
bufferline = "always"
text-width = 96
cursorline = true
rulers = [96]
true-color = true

[editor.indent-guides]
render = true

[keys.normal]
"A-," = "goto_previous_buffer"
"A-." = "goto_next_buffer"
"A-w" = ":buffer-close"
"A-/" = "repeat_last_motion"

